name: C/C++ CI

on:
#   push:
#     branches: [ "master" ]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-SDL mingw-w64-x86_64-SDL_net
      - name: Find-SDL
        run: pwd
      - name: CI-Build
        run: mingw32-make -f Makefiles/Makefile.Win32 NET_BOARD=1
  findSDL:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw64/mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-make mingw64/mingw-w64-x86_64-SDL mingw64/mingw-w64-x86_64-SDL_net
      - name: Find-SDL-include
        run: cd ../.. && ls ./_temp/msys64/mingw64/include/SDL && Get-CurrentLocation
      - name: Find-SDL-libs
        run: cd ../..  && ls ./_temp/msys64/mingw64/lib && Get-CurrentLocation
        
