name: CI-Win64

on:
  workflow_dispatch:
  # push:
  #  branches:
  #   - master
      
permissions:
  contents: read
  
jobs:
  CI-Win64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
   
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          install: make mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_net
          
      - uses: actions/checkout@v3
      
      - name: Compile
        run: make -f MakeFiles/MakeFile.Win32 -j$($(nproc) + 1)
          
      - name: Stage
        run: |
          mkdir -p pkg/NVRAM
          mkdir -p pkg/Saves
          mkdir -p pkg/ROMs
          echo "NVRAM files go here." > pkg/NVRAM/DIR.txt
          echo "Save states go here." > pkg/Saves/DIR.txt
          echo "Recommended \(but not mandatory) location for ROM sets." > pkg/ROMs/DIR.txt
          cp -r Config pkg/Config
          cp Docs/README.txt pkg
          cp Docs/LICENSE.txt pkg
          cp bin64/supermodel.exe pkg/Supermodel.exe

      - uses: actions/upload-artifact@v3
        with:
          name: Supermodel
          path: pkg/
